
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 34;
  public static final int LBRACKET = 28;
  public static final int MULT = 11;
  public static final int LPAREN = 24;
  public static final int INT = 2;
  public static final int MINUS = 10;
  public static final int RPAREN = 25;
  public static final int NOT = 22;
  public static final int SEMICOLON = 31;
  public static final int AND = 20;
  public static final int LT = 18;
  public static final int OR = 21;
  public static final int COMMA = 30;
  public static final int DIV = 12;
  public static final int GEQ = 17;
  public static final int PLUS = 9;
  public static final int ASSIGN = 23;
  public static final int IF = 4;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int RBRACKET = 29;
  public static final int error = 1;
  public static final int MOD = 13;
  public static final int NEQ = 15;
  public static final int VOID = 8;
  public static final int EQ = 14;
  public static final int LBRACE = 26;
  public static final int ELSE = 5;
  public static final int WHILE = 6;
  public static final int FLOAT = 3;
  public static final int RBRACE = 27;
  public static final int LEQ = 16;
  public static final int STRING_LIT = 35;
  public static final int INT_LIT = 33;
  public static final int GT = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "VOID",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "EQ",
  "NEQ",
  "LEQ",
  "GEQ",
  "LT",
  "GT",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "SEMICOLON",
  "ID",
  "INT_LIT",
  "FLOAT_LIT",
  "STRING_LIT"
  };

  /* non terminals */
  static final int param = 11;
  static final int stmt = 5;
  static final int params = 10;
  static final int decl_list = 1;
  static final int program = 0;
  static final int args_opt = 7;
  static final int args = 8;
  static final int type = 3;
  static final int decl = 2;
  static final int expr = 6;
  static final int stmt_list = 4;
  static final int params_opt = 9;
}

